/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.app.view;

/**
 *
 * @author carlos
 */
public class PanelVisualizationProduct extends javax.swing.JPanel {

    /**
     * Creates new form PanelVisualizationProduct
     */
    public PanelVisualizationProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCodProd = new javax.swing.JLabel();
        txtSearchProd = new javax.swing.JTextField();
        lblSearchProd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPriceProd = new javax.swing.JTextField();
        lblPriceProd = new javax.swing.JLabel();
        lblNameProd = new javax.swing.JLabel();
        txtNameProd = new javax.swing.JTextField();
        lblTypeProd = new javax.swing.JLabel();
        jcbTypeProd = new javax.swing.JComboBox<>();
        lblTypeProd1 = new javax.swing.JLabel();
        lblTypeProd2 = new javax.swing.JLabel();
        txtPriceProd1 = new javax.swing.JTextField();
        lblPriceProd1 = new javax.swing.JLabel();
        txtPriceProd2 = new javax.swing.JTextField();
        txtPriceProd3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jcbTypeProd1 = new javax.swing.JComboBox<>();
        lblPriceProd2 = new javax.swing.JLabel();
        lblPriceProd3 = new javax.swing.JLabel();
        txtNameProd1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 60, 85)));
        setMaximumSize(new java.awt.Dimension(551, 398));
        setMinimumSize(new java.awt.Dimension(551, 398));
        setPreferredSize(new java.awt.Dimension(551, 398));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(145, 4, 72));
        jPanel2.setPreferredSize(new java.awt.Dimension(520, 49));

        lblCodProd.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblCodProd.setForeground(new java.awt.Color(255, 255, 255));
        lblCodProd.setText("10");

        txtSearchProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchProdActionPerformed(evt);
            }
        });

        lblSearchProd.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        lblSearchProd.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchProd.setText("Buscar:");

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salvar");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adicionar Produto");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Editar");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Remover");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Adicionar Preço Venda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchProd)
                .addGap(18, 18, 18)
                .addComponent(txtSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodProd)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchProd)
                    .addComponent(lblCodProd)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30))
        );

        txtPriceProd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPriceProd.setEnabled(false);

        lblPriceProd.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblPriceProd.setForeground(new java.awt.Color(0, 102, 102));
        lblPriceProd.setText("*Preço:");

        lblNameProd.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblNameProd.setForeground(new java.awt.Color(0, 102, 102));
        lblNameProd.setText("*Nome Produto:");

        txtNameProd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameProd.setEnabled(false);

        lblTypeProd.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblTypeProd.setForeground(new java.awt.Color(0, 102, 102));
        lblTypeProd.setText("Tipo Produto:");

        jcbTypeProd.setEnabled(false);

        lblTypeProd1.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblTypeProd1.setForeground(new java.awt.Color(0, 102, 102));
        lblTypeProd1.setText("*Total:");

        lblTypeProd2.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblTypeProd2.setForeground(new java.awt.Color(0, 102, 102));
        lblTypeProd2.setText("Código Adicional:");

        txtPriceProd1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPriceProd1.setEnabled(false);

        lblPriceProd1.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblPriceProd1.setForeground(new java.awt.Color(0, 102, 102));
        lblPriceProd1.setText("*Quantidade:");

        txtPriceProd2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPriceProd2.setEnabled(false);

        txtPriceProd3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPriceProd3.setEnabled(false);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 102, 102));
        jCheckBox1.setText("Ativo");

        jcbTypeProd1.setEnabled(false);

        lblPriceProd2.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblPriceProd2.setForeground(new java.awt.Color(0, 102, 102));
        lblPriceProd2.setText("Nome Parceiro:");

        lblPriceProd3.setFont(new java.awt.Font("Segoe UI Light", 0, 8)); // NOI18N
        lblPriceProd3.setForeground(new java.awt.Color(0, 102, 102));
        lblPriceProd3.setText("Descrição:");

        txtNameProd1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameProd1.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNameProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameProd, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTypeProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblTypeProd2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPriceProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jcbTypeProd1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblPriceProd2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriceProd3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblPriceProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPriceProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPriceProd1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPriceProd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTypeProd1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPriceProd3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1))
                            .addComponent(txtNameProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeProd)
                    .addComponent(txtNameProd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameProd)
                    .addComponent(jcbTypeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceProd)
                    .addComponent(txtPriceProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceProd1)
                    .addComponent(txtPriceProd2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeProd1)
                    .addComponent(txtPriceProd3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(lblTypeProd2)
                    .addComponent(txtPriceProd, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceProd2)
                    .addComponent(lblPriceProd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTypeProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbTypeProd;
    private javax.swing.JComboBox<String> jcbTypeProd1;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblNameProd;
    private javax.swing.JLabel lblPriceProd;
    private javax.swing.JLabel lblPriceProd1;
    private javax.swing.JLabel lblPriceProd2;
    private javax.swing.JLabel lblPriceProd3;
    private javax.swing.JLabel lblSearchProd;
    private javax.swing.JLabel lblTypeProd;
    private javax.swing.JLabel lblTypeProd1;
    private javax.swing.JLabel lblTypeProd2;
    private javax.swing.JTextField txtNameProd;
    private javax.swing.JTextField txtNameProd1;
    private javax.swing.JTextField txtPriceProd;
    private javax.swing.JTextField txtPriceProd1;
    private javax.swing.JTextField txtPriceProd2;
    private javax.swing.JTextField txtPriceProd3;
    private javax.swing.JTextField txtSearchProd;
    // End of variables declaration//GEN-END:variables
}
